3 nowe klasy
H4nss/Projekt1 pull request #7
Opened 2022-03-15 13:43 UTC by MrZuXii

Stworzyłem 3 klasy. 
Pierwsza "interface" udostępnia w ogólnym skrócie interfejs programu typu: menu programu, ekran logowania, ukrycie wpisywania hasła zmieniając je na gwiazdki

Druga "authorization"   sprawdza czy uzytkownik podczas logowania podał poprawne dane wykorzystuje do tego plik user.dat w kalalogu data
np. jeżeli plik ma nazwe wincent.dat to jako login sprawdza nazwe pliku a jako hasło pierwszą linijke w tym pliku.

Trzecia "balanceuser" udostępnia informacje o salcie użytkownika wykorzystując drugą linijke w pliku.

2022-03-15 19:57 UTC, watFiree commented
@MrZuXii testowałeś czy to działa? bo z tego co wiem, mechanika powinna byc w pliku z rozszerzeniem .cpp, tak jak to opisałem na kanale "jak-tworzyć-klasy"

2022-03-15 20:08 UTC, watFiree commented on src/classes/authorization.h
> +class authorization
nazwy klas raczej zaczynamy z dużej

2022-03-15 20:08 UTC, watFiree commented on src/classes/authorization.h
> +    bool IsUserExist(string username, string password);
doesUserExist

2022-03-15 20:08 UTC, watFiree commented on src/classes/balanceuser.h
> +#include <iomanip> //for std::setprecision
ten komentarz raczej do wywalenia

2022-03-15 20:08 UTC, watFiree commented on src/classes/balanceuser.h
> +class balanceuser
Klasa z dużej

2022-03-15 20:08 UTC, watFiree commented on src/classes/balanceuser.h
> +long double balanceuser::Balance(const std::string username, bool auth)
nazwa tej funkcji nie mów wgl co robi, nazwijmy ją np. getBalance

2022-03-15 20:08 UTC, watFiree commented on src/classes/balanceuser.h
> +        long double b = std::stold(balancestring);
ta zmienna nie informujme czym jest, nazwijmy ją jakoś albo odrazu zróbmy return'a z tą funkcją

2022-03-15 20:08 UTC, watFiree commented on src/classes/balanceuser.h
> +    else
zbędny else, jak robimy wyżej `return`

2022-03-15 20:08 UTC, watFiree commented on src/classes/interface.h
> +    bool auth;                   // Zmienna przechowująca czy użytkownik jest poprawnie zalogowany
jak mamy zmienna bool to zróbmy nop. isAuthorized

2022-03-15 20:08 UTC, watFiree commented on src/classes/interface.h
> +    std::cout << "          Nazwa konta                           Salto\n";
tu mamy chyba literówke : Saldo

2022-03-15 20:24 UTC, watFiree requested changes

2022-03-15 20:24 UTC, watFiree commented on src/classes/authorization.h
> +    fstream plik(path, std::ios::in); // zakładamy, że plik istnieje
nie chciałoby ci się zrobić np funkcji, albo najlepiej klasy np `Database` i ona by miała metody save i get , i do takiej metody byśmy przekazywali fileName, a już w niej ustalalibyśmy path itp.?

2022-03-17 18:17 UTC, MrZuXii commented on src/classes/authorization.h
> +    bool IsUserExist(string username, string password);
Zrobiłem

2022-03-22 18:23 UTC, watFiree reviewed
@MrZuXii pogrupuj jeszcze te pliki w foldery tak jak `User`

2022-04-03 15:53 UTC, watFiree reviewed
Osobiscie nie widze sensu istnienia klas:

- Balanceuser 
- Authorization

Cala ta logika mogla by sie znalesc w Userze, ktorego mamy na glownej galezi. Tj. w nim mielibysmy wlasciowsc isAuthorized i metode getBalance. Co o tym myslicie @jakubdziadkowiec @H4nss ?

2022-05-17 19:50 UTC, closed without merging